#pragma once
#include "NativeGameplayTags.h"

namespace WarGameTags
{
	WAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);
	WAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look);
	WAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Jump);
	WAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_MouseLook);
	WAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_LightAttack);
	WAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_HeavyAttack);
	WAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Inventory);
	WAR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Character);
}
